apiVersion: v1
kind: Service
metadata:
  name: devpilot-backend-service
spec:
  selector:
    app: devpilot-backend-app
  ports:
    - protocol: TCP
      port: 8182
      targetPort: 8182
  type: ClusterIP