apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/backend

images:
  - name: vkflco08/devpilot # base/backend/deployment.yaml에 있는 이미지 이름
    newTag: build-34-20250722080913