apiVersion: apps/v1
kind: Deployment
metadata:
  name: devpilot-app
  namespace: devpilot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devpilot-app
  template:
    metadata:
      labels:
        app: devpilot-app
    spec:
      containers:
        - name: devpilot-app
          image: "vkflco08/devpilot:latest"
          ports:
            - containerPort: 8182
