apiVersion: v1
kind: Service
metadata:
  name: devpilot
  namespace: devpilot
spec:
  selector:
    app: devpilot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8182
  type: LoadBalancer
